### ISSUE TITLE
Check the state

### ISSUE THREAD

**Issue by fabaff** [simplepush/simplepush-python#5]
Now, if the sending of a message fails then it will fail silently. As far as I remember is a feedback available from simplepush.io. We handled it through the response because we [moved](https://github.com/home-assistant/home-assistant/pull/9568) to `simplepush-python` with Home Assistant. 

Raising an error would be be most elegant way:

```
if response.json()['status'] != 'OK':
   raise SomeError("Unable to send notification")
```

**Comment by simplepush** [comment]
Done.
